#!/usr/bin/env bun
// Injects the release signing config into Tauri's generated Android
// `build.gradle.kts`.
//
// `gen/android` is gitignored and regenerated by `tauri android init`, so the
// signing block can't just live in a committed file — it has to be re-applied
// after init on every CI run. This does that, driven by a `keystore.properties`
// written from CI secrets (see the workflow).
//
// It's idempotent (safe to run twice) and fails loudly if Tauri's generated
// file changes shape, so CI errors clearly instead of silently shipping an
// unsigned APK.
//
// Run it from `apps/desktop/src-tauri`:  bun scripts/patch-android-signing.ts

import {
    readFileSync,
    writeFileSync,
} from "node:fs";

const GRADLE_PATH = "gen/android/app/build.gradle.kts";

function fail(anchor: string): never {
    console.error(`[patch-android-signing] anchor not found: ${anchor}`);
    console.error(
        "Tauri's generated build.gradle.kts changed shape — update this script.",
    );
    process.exit(1);
}

let src = readFileSync(GRADLE_PATH, "utf8");

if (src.includes("signingConfigs {")) {
    console.log("[patch-android-signing] already patched, skipping");
    process.exit(0);
}

// 1. Import needed by the signing block.
const IMPORT_ANCHOR = "import java.util.Properties\n";
if (!src.includes(IMPORT_ANCHOR)) fail("import java.util.Properties");
if (!src.includes("import java.io.FileInputStream")) {
    src = src.replace(
        IMPORT_ANCHOR,
        IMPORT_ANCHOR + "import java.io.FileInputStream\n",
    );
}

// 2. The signing config itself, inserted just before `buildTypes`.
const BUILD_TYPES_ANCHOR = "    buildTypes {";
if (!src.includes(BUILD_TYPES_ANCHOR)) fail("buildTypes block");

const SIGNING_BLOCK = `    signingConfigs {
        create("release") {
            val keystorePropertiesFile = rootProject.file("keystore.properties")
            val keystoreProperties = Properties()
            if (keystorePropertiesFile.exists()) {
                keystoreProperties.load(FileInputStream(keystorePropertiesFile))
            }
            keyAlias = keystoreProperties["keyAlias"] as String
            keyPassword = keystoreProperties["password"] as String
            storeFile = file(keystoreProperties["storeFile"] as String)
            storePassword = keystoreProperties["password"] as String
        }
    }
`;
src = src.replace(BUILD_TYPES_ANCHOR, SIGNING_BLOCK + BUILD_TYPES_ANCHOR);

// 3. Wire that config into the existing `release` build type.
const RELEASE_ANCHOR = `        getByName("release") {\n`;
if (!src.includes(RELEASE_ANCHOR)) fail(`getByName("release")`);
src = src.replace(
    RELEASE_ANCHOR,
    RELEASE_ANCHOR +
        `            signingConfig = signingConfigs.getByName("release")\n`,
);

writeFileSync(GRADLE_PATH, src);
console.log("[patch-android-signing] signing config injected");
